default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: rails_kadai2_development

test:
  <<: *default
  database: rails_kadai2_test

production:
  <<: *default
  database: rails_kadai2_production
  username: rails_kadai2
  password: <%= ENV['RAILS_KADAI2_DATABASE_PASSWORD'] %>
